// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

type AnalysisAssetKind string

const (
	AnalysisAssetKindGarmentCrop AnalysisAssetKind = "garment_crop"
	AnalysisAssetKindPhonePhoto  AnalysisAssetKind = "phone_photo"
)

func (e *AnalysisAssetKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalysisAssetKind(s)
	case string:
		*e = AnalysisAssetKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalysisAssetKind: %T", src)
	}
	return nil
}

type NullAnalysisAssetKind struct {
	AnalysisAssetKind AnalysisAssetKind
	Valid             bool // Valid is true if AnalysisAssetKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalysisAssetKind) Scan(value interface{}) error {
	if value == nil {
		ns.AnalysisAssetKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalysisAssetKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalysisAssetKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalysisAssetKind), nil
}

func (e AnalysisAssetKind) Valid() bool {
	switch e {
	case AnalysisAssetKindGarmentCrop,
		AnalysisAssetKindPhonePhoto:
		return true
	}
	return false
}

func AllAnalysisAssetKindValues() []AnalysisAssetKind {
	return []AnalysisAssetKind{
		AnalysisAssetKindGarmentCrop,
		AnalysisAssetKindPhonePhoto,
	}
}

type CandidateResolution string

const (
	CandidateResolutionPending   CandidateResolution = "pending"
	CandidateResolutionAuto      CandidateResolution = "auto"
	CandidateResolutionConfirmed CandidateResolution = "confirmed"
	CandidateResolutionCorrected CandidateResolution = "corrected"
	CandidateResolutionNew       CandidateResolution = "new"
	CandidateResolutionUnknown   CandidateResolution = "unknown"
)

func (e *CandidateResolution) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CandidateResolution(s)
	case string:
		*e = CandidateResolution(s)
	default:
		return fmt.Errorf("unsupported scan type for CandidateResolution: %T", src)
	}
	return nil
}

type NullCandidateResolution struct {
	CandidateResolution CandidateResolution
	Valid               bool // Valid is true if CandidateResolution is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCandidateResolution) Scan(value interface{}) error {
	if value == nil {
		ns.CandidateResolution, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CandidateResolution.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCandidateResolution) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CandidateResolution), nil
}

func (e CandidateResolution) Valid() bool {
	switch e {
	case CandidateResolutionPending,
		CandidateResolutionAuto,
		CandidateResolutionConfirmed,
		CandidateResolutionCorrected,
		CandidateResolutionNew,
		CandidateResolutionUnknown:
		return true
	}
	return false
}

func AllCandidateResolutionValues() []CandidateResolution {
	return []CandidateResolution{
		CandidateResolutionPending,
		CandidateResolutionAuto,
		CandidateResolutionConfirmed,
		CandidateResolutionCorrected,
		CandidateResolutionNew,
		CandidateResolutionUnknown,
	}
}

type CaptureSource string

const (
	CaptureSourceCatalog  CaptureSource = "catalog"
	CaptureSourcePhoneFit CaptureSource = "phone_fit"
	CaptureSourceMirror   CaptureSource = "mirror"
)

func (e *CaptureSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CaptureSource(s)
	case string:
		*e = CaptureSource(s)
	default:
		return fmt.Errorf("unsupported scan type for CaptureSource: %T", src)
	}
	return nil
}

type NullCaptureSource struct {
	CaptureSource CaptureSource
	Valid         bool // Valid is true if CaptureSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCaptureSource) Scan(value interface{}) error {
	if value == nil {
		ns.CaptureSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CaptureSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCaptureSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CaptureSource), nil
}

func (e CaptureSource) Valid() bool {
	switch e {
	case CaptureSourceCatalog,
		CaptureSourcePhoneFit,
		CaptureSourceMirror:
		return true
	}
	return false
}

func AllCaptureSourceValues() []CaptureSource {
	return []CaptureSource{
		CaptureSourceCatalog,
		CaptureSourcePhoneFit,
		CaptureSourceMirror,
	}
}

type ColorFamily string

const (
	ColorFamilyBlack    ColorFamily = "black"
	ColorFamilyWhite    ColorFamily = "white"
	ColorFamilyGrey     ColorFamily = "grey"
	ColorFamilyCream    ColorFamily = "cream"
	ColorFamilyBeige    ColorFamily = "beige"
	ColorFamilyTan      ColorFamily = "tan"
	ColorFamilyBrown    ColorFamily = "brown"
	ColorFamilyNavy     ColorFamily = "navy"
	ColorFamilyBlue     ColorFamily = "blue"
	ColorFamilyGreen    ColorFamily = "green"
	ColorFamilyOlive    ColorFamily = "olive"
	ColorFamilyRed      ColorFamily = "red"
	ColorFamilyBurgundy ColorFamily = "burgundy"
	ColorFamilyPink     ColorFamily = "pink"
	ColorFamilyOrange   ColorFamily = "orange"
	ColorFamilyYellow   ColorFamily = "yellow"
	ColorFamilyPurple   ColorFamily = "purple"
	ColorFamilyMulti    ColorFamily = "multi"
)

func (e *ColorFamily) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ColorFamily(s)
	case string:
		*e = ColorFamily(s)
	default:
		return fmt.Errorf("unsupported scan type for ColorFamily: %T", src)
	}
	return nil
}

type NullColorFamily struct {
	ColorFamily ColorFamily
	Valid       bool // Valid is true if ColorFamily is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullColorFamily) Scan(value interface{}) error {
	if value == nil {
		ns.ColorFamily, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ColorFamily.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullColorFamily) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ColorFamily), nil
}

func (e ColorFamily) Valid() bool {
	switch e {
	case ColorFamilyBlack,
		ColorFamilyWhite,
		ColorFamilyGrey,
		ColorFamilyCream,
		ColorFamilyBeige,
		ColorFamilyTan,
		ColorFamilyBrown,
		ColorFamilyNavy,
		ColorFamilyBlue,
		ColorFamilyGreen,
		ColorFamilyOlive,
		ColorFamilyRed,
		ColorFamilyBurgundy,
		ColorFamilyPink,
		ColorFamilyOrange,
		ColorFamilyYellow,
		ColorFamilyPurple,
		ColorFamilyMulti:
		return true
	}
	return false
}

func AllColorFamilyValues() []ColorFamily {
	return []ColorFamily{
		ColorFamilyBlack,
		ColorFamilyWhite,
		ColorFamilyGrey,
		ColorFamilyCream,
		ColorFamilyBeige,
		ColorFamilyTan,
		ColorFamilyBrown,
		ColorFamilyNavy,
		ColorFamilyBlue,
		ColorFamilyGreen,
		ColorFamilyOlive,
		ColorFamilyRed,
		ColorFamilyBurgundy,
		ColorFamilyPink,
		ColorFamilyOrange,
		ColorFamilyYellow,
		ColorFamilyPurple,
		ColorFamilyMulti,
	}
}

type ExemplarCreationReason string

const (
	ExemplarCreationReasonInitial      ExemplarCreationReason = "initial"
	ExemplarCreationReasonConfirmation ExemplarCreationReason = "confirmation"
	ExemplarCreationReasonCorrection   ExemplarCreationReason = "correction"
	ExemplarCreationReasonNewGarment   ExemplarCreationReason = "new_garment"
)

func (e *ExemplarCreationReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExemplarCreationReason(s)
	case string:
		*e = ExemplarCreationReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ExemplarCreationReason: %T", src)
	}
	return nil
}

type NullExemplarCreationReason struct {
	ExemplarCreationReason ExemplarCreationReason
	Valid                  bool // Valid is true if ExemplarCreationReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExemplarCreationReason) Scan(value interface{}) error {
	if value == nil {
		ns.ExemplarCreationReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExemplarCreationReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExemplarCreationReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExemplarCreationReason), nil
}

func (e ExemplarCreationReason) Valid() bool {
	switch e {
	case ExemplarCreationReasonInitial,
		ExemplarCreationReasonConfirmation,
		ExemplarCreationReasonCorrection,
		ExemplarCreationReasonNewGarment:
		return true
	}
	return false
}

func AllExemplarCreationReasonValues() []ExemplarCreationReason {
	return []ExemplarCreationReason{
		ExemplarCreationReasonInitial,
		ExemplarCreationReasonConfirmation,
		ExemplarCreationReasonCorrection,
		ExemplarCreationReasonNewGarment,
	}
}

type GarmentCategory string

const (
	GarmentCategoryTShirt         GarmentCategory = "t_shirt"
	GarmentCategoryShirt          GarmentCategory = "shirt"
	GarmentCategoryPolo           GarmentCategory = "polo"
	GarmentCategoryBlouse         GarmentCategory = "blouse"
	GarmentCategoryTankTop        GarmentCategory = "tank_top"
	GarmentCategorySweater        GarmentCategory = "sweater"
	GarmentCategorySweatshirt     GarmentCategory = "sweatshirt"
	GarmentCategoryHoodie         GarmentCategory = "hoodie"
	GarmentCategoryCardigan       GarmentCategory = "cardigan"
	GarmentCategoryOvershirt      GarmentCategory = "overshirt"
	GarmentCategoryOtherTop       GarmentCategory = "other_top"
	GarmentCategoryJeans          GarmentCategory = "jeans"
	GarmentCategoryTrousers       GarmentCategory = "trousers"
	GarmentCategoryChinos         GarmentCategory = "chinos"
	GarmentCategoryShorts         GarmentCategory = "shorts"
	GarmentCategorySkirt          GarmentCategory = "skirt"
	GarmentCategorySweatpants     GarmentCategory = "sweatpants"
	GarmentCategoryLeggings       GarmentCategory = "leggings"
	GarmentCategoryOtherBottom    GarmentCategory = "other_bottom"
	GarmentCategoryDress          GarmentCategory = "dress"
	GarmentCategoryJumpsuit       GarmentCategory = "jumpsuit"
	GarmentCategoryOtherOnePiece  GarmentCategory = "other_one_piece"
	GarmentCategoryJacket         GarmentCategory = "jacket"
	GarmentCategoryBlazer         GarmentCategory = "blazer"
	GarmentCategoryCoat           GarmentCategory = "coat"
	GarmentCategoryVest           GarmentCategory = "vest"
	GarmentCategoryOtherOuterwear GarmentCategory = "other_outerwear"
	GarmentCategorySneakers       GarmentCategory = "sneakers"
	GarmentCategoryBoots          GarmentCategory = "boots"
	GarmentCategoryLoafers        GarmentCategory = "loafers"
	GarmentCategoryDressShoes     GarmentCategory = "dress_shoes"
	GarmentCategorySandals        GarmentCategory = "sandals"
	GarmentCategoryOtherFootwear  GarmentCategory = "other_footwear"
	GarmentCategoryHat            GarmentCategory = "hat"
	GarmentCategoryBeanie         GarmentCategory = "beanie"
	GarmentCategoryScarf          GarmentCategory = "scarf"
	GarmentCategoryGloves         GarmentCategory = "gloves"
	GarmentCategoryBelt           GarmentCategory = "belt"
	GarmentCategoryBag            GarmentCategory = "bag"
	GarmentCategorySunglasses     GarmentCategory = "sunglasses"
	GarmentCategoryWatch          GarmentCategory = "watch"
	GarmentCategoryJewelry        GarmentCategory = "jewelry"
	GarmentCategorySocks          GarmentCategory = "socks"
	GarmentCategoryTie            GarmentCategory = "tie"
	GarmentCategoryOtherAccessory GarmentCategory = "other_accessory"
)

func (e *GarmentCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GarmentCategory(s)
	case string:
		*e = GarmentCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for GarmentCategory: %T", src)
	}
	return nil
}

type NullGarmentCategory struct {
	GarmentCategory GarmentCategory
	Valid           bool // Valid is true if GarmentCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGarmentCategory) Scan(value interface{}) error {
	if value == nil {
		ns.GarmentCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GarmentCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGarmentCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GarmentCategory), nil
}

func (e GarmentCategory) Valid() bool {
	switch e {
	case GarmentCategoryTShirt,
		GarmentCategoryShirt,
		GarmentCategoryPolo,
		GarmentCategoryBlouse,
		GarmentCategoryTankTop,
		GarmentCategorySweater,
		GarmentCategorySweatshirt,
		GarmentCategoryHoodie,
		GarmentCategoryCardigan,
		GarmentCategoryOvershirt,
		GarmentCategoryOtherTop,
		GarmentCategoryJeans,
		GarmentCategoryTrousers,
		GarmentCategoryChinos,
		GarmentCategoryShorts,
		GarmentCategorySkirt,
		GarmentCategorySweatpants,
		GarmentCategoryLeggings,
		GarmentCategoryOtherBottom,
		GarmentCategoryDress,
		GarmentCategoryJumpsuit,
		GarmentCategoryOtherOnePiece,
		GarmentCategoryJacket,
		GarmentCategoryBlazer,
		GarmentCategoryCoat,
		GarmentCategoryVest,
		GarmentCategoryOtherOuterwear,
		GarmentCategorySneakers,
		GarmentCategoryBoots,
		GarmentCategoryLoafers,
		GarmentCategoryDressShoes,
		GarmentCategorySandals,
		GarmentCategoryOtherFootwear,
		GarmentCategoryHat,
		GarmentCategoryBeanie,
		GarmentCategoryScarf,
		GarmentCategoryGloves,
		GarmentCategoryBelt,
		GarmentCategoryBag,
		GarmentCategorySunglasses,
		GarmentCategoryWatch,
		GarmentCategoryJewelry,
		GarmentCategorySocks,
		GarmentCategoryTie,
		GarmentCategoryOtherAccessory:
		return true
	}
	return false
}

func AllGarmentCategoryValues() []GarmentCategory {
	return []GarmentCategory{
		GarmentCategoryTShirt,
		GarmentCategoryShirt,
		GarmentCategoryPolo,
		GarmentCategoryBlouse,
		GarmentCategoryTankTop,
		GarmentCategorySweater,
		GarmentCategorySweatshirt,
		GarmentCategoryHoodie,
		GarmentCategoryCardigan,
		GarmentCategoryOvershirt,
		GarmentCategoryOtherTop,
		GarmentCategoryJeans,
		GarmentCategoryTrousers,
		GarmentCategoryChinos,
		GarmentCategoryShorts,
		GarmentCategorySkirt,
		GarmentCategorySweatpants,
		GarmentCategoryLeggings,
		GarmentCategoryOtherBottom,
		GarmentCategoryDress,
		GarmentCategoryJumpsuit,
		GarmentCategoryOtherOnePiece,
		GarmentCategoryJacket,
		GarmentCategoryBlazer,
		GarmentCategoryCoat,
		GarmentCategoryVest,
		GarmentCategoryOtherOuterwear,
		GarmentCategorySneakers,
		GarmentCategoryBoots,
		GarmentCategoryLoafers,
		GarmentCategoryDressShoes,
		GarmentCategorySandals,
		GarmentCategoryOtherFootwear,
		GarmentCategoryHat,
		GarmentCategoryBeanie,
		GarmentCategoryScarf,
		GarmentCategoryGloves,
		GarmentCategoryBelt,
		GarmentCategoryBag,
		GarmentCategorySunglasses,
		GarmentCategoryWatch,
		GarmentCategoryJewelry,
		GarmentCategorySocks,
		GarmentCategoryTie,
		GarmentCategoryOtherAccessory,
	}
}

type GarmentFit string

const (
	GarmentFitRelaxed GarmentFit = "relaxed"
	GarmentFitRegular GarmentFit = "regular"
	GarmentFitSlim    GarmentFit = "slim"
)

func (e *GarmentFit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GarmentFit(s)
	case string:
		*e = GarmentFit(s)
	default:
		return fmt.Errorf("unsupported scan type for GarmentFit: %T", src)
	}
	return nil
}

type NullGarmentFit struct {
	GarmentFit GarmentFit
	Valid      bool // Valid is true if GarmentFit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGarmentFit) Scan(value interface{}) error {
	if value == nil {
		ns.GarmentFit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GarmentFit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGarmentFit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GarmentFit), nil
}

func (e GarmentFit) Valid() bool {
	switch e {
	case GarmentFitRelaxed,
		GarmentFitRegular,
		GarmentFitSlim:
		return true
	}
	return false
}

func AllGarmentFitValues() []GarmentFit {
	return []GarmentFit{
		GarmentFitRelaxed,
		GarmentFitRegular,
		GarmentFitSlim,
	}
}

type GarmentMaterial string

const (
	GarmentMaterialCotton    GarmentMaterial = "cotton"
	GarmentMaterialLinen     GarmentMaterial = "linen"
	GarmentMaterialWool      GarmentMaterial = "wool"
	GarmentMaterialCashmere  GarmentMaterial = "cashmere"
	GarmentMaterialSilk      GarmentMaterial = "silk"
	GarmentMaterialDenim     GarmentMaterial = "denim"
	GarmentMaterialLeather   GarmentMaterial = "leather"
	GarmentMaterialSuede     GarmentMaterial = "suede"
	GarmentMaterialPolyester GarmentMaterial = "polyester"
	GarmentMaterialNylon     GarmentMaterial = "nylon"
	GarmentMaterialFleece    GarmentMaterial = "fleece"
	GarmentMaterialViscose   GarmentMaterial = "viscose"
	GarmentMaterialOther     GarmentMaterial = "other"
)

func (e *GarmentMaterial) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GarmentMaterial(s)
	case string:
		*e = GarmentMaterial(s)
	default:
		return fmt.Errorf("unsupported scan type for GarmentMaterial: %T", src)
	}
	return nil
}

type NullGarmentMaterial struct {
	GarmentMaterial GarmentMaterial
	Valid           bool // Valid is true if GarmentMaterial is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGarmentMaterial) Scan(value interface{}) error {
	if value == nil {
		ns.GarmentMaterial, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GarmentMaterial.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGarmentMaterial) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GarmentMaterial), nil
}

func (e GarmentMaterial) Valid() bool {
	switch e {
	case GarmentMaterialCotton,
		GarmentMaterialLinen,
		GarmentMaterialWool,
		GarmentMaterialCashmere,
		GarmentMaterialSilk,
		GarmentMaterialDenim,
		GarmentMaterialLeather,
		GarmentMaterialSuede,
		GarmentMaterialPolyester,
		GarmentMaterialNylon,
		GarmentMaterialFleece,
		GarmentMaterialViscose,
		GarmentMaterialOther:
		return true
	}
	return false
}

func AllGarmentMaterialValues() []GarmentMaterial {
	return []GarmentMaterial{
		GarmentMaterialCotton,
		GarmentMaterialLinen,
		GarmentMaterialWool,
		GarmentMaterialCashmere,
		GarmentMaterialSilk,
		GarmentMaterialDenim,
		GarmentMaterialLeather,
		GarmentMaterialSuede,
		GarmentMaterialPolyester,
		GarmentMaterialNylon,
		GarmentMaterialFleece,
		GarmentMaterialViscose,
		GarmentMaterialOther,
	}
}

type GarmentPattern string

const (
	GarmentPatternSolid    GarmentPattern = "solid"
	GarmentPatternStriped  GarmentPattern = "striped"
	GarmentPatternChecked  GarmentPattern = "checked"
	GarmentPatternPlaid    GarmentPattern = "plaid"
	GarmentPatternFloral   GarmentPattern = "floral"
	GarmentPatternGraphic  GarmentPattern = "graphic"
	GarmentPatternTextured GarmentPattern = "textured"
	GarmentPatternOther    GarmentPattern = "other"
)

func (e *GarmentPattern) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GarmentPattern(s)
	case string:
		*e = GarmentPattern(s)
	default:
		return fmt.Errorf("unsupported scan type for GarmentPattern: %T", src)
	}
	return nil
}

type NullGarmentPattern struct {
	GarmentPattern GarmentPattern
	Valid          bool // Valid is true if GarmentPattern is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGarmentPattern) Scan(value interface{}) error {
	if value == nil {
		ns.GarmentPattern, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GarmentPattern.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGarmentPattern) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GarmentPattern), nil
}

func (e GarmentPattern) Valid() bool {
	switch e {
	case GarmentPatternSolid,
		GarmentPatternStriped,
		GarmentPatternChecked,
		GarmentPatternPlaid,
		GarmentPatternFloral,
		GarmentPatternGraphic,
		GarmentPatternTextured,
		GarmentPatternOther:
		return true
	}
	return false
}

func AllGarmentPatternValues() []GarmentPattern {
	return []GarmentPattern{
		GarmentPatternSolid,
		GarmentPatternStriped,
		GarmentPatternChecked,
		GarmentPatternPlaid,
		GarmentPatternFloral,
		GarmentPatternGraphic,
		GarmentPatternTextured,
		GarmentPatternOther,
	}
}

type ImageKind string

const (
	ImageKindRawFrame     ImageKind = "raw_frame"
	ImageKindPhonePhoto   ImageKind = "phone_photo"
	ImageKindGarmentCrop  ImageKind = "garment_crop"
	ImageKindCatalogPhoto ImageKind = "catalog_photo"
)

func (e *ImageKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImageKind(s)
	case string:
		*e = ImageKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ImageKind: %T", src)
	}
	return nil
}

type NullImageKind struct {
	ImageKind ImageKind
	Valid     bool // Valid is true if ImageKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImageKind) Scan(value interface{}) error {
	if value == nil {
		ns.ImageKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImageKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImageKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImageKind), nil
}

func (e ImageKind) Valid() bool {
	switch e {
	case ImageKindRawFrame,
		ImageKindPhonePhoto,
		ImageKindGarmentCrop,
		ImageKindCatalogPhoto:
		return true
	}
	return false
}

func AllImageKindValues() []ImageKind {
	return []ImageKind{
		ImageKindRawFrame,
		ImageKindPhonePhoto,
		ImageKindGarmentCrop,
		ImageKindCatalogPhoto,
	}
}

type ImagePurpose string

const (
	ImagePurposeDetect   ImagePurpose = "detect"
	ImagePurposeEmbed    ImagePurpose = "embed"
	ImagePurposeCritique ImagePurpose = "critique"
	ImagePurposeSegment  ImagePurpose = "segment"
)

func (e *ImagePurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImagePurpose(s)
	case string:
		*e = ImagePurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for ImagePurpose: %T", src)
	}
	return nil
}

type NullImagePurpose struct {
	ImagePurpose ImagePurpose
	Valid        bool // Valid is true if ImagePurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImagePurpose) Scan(value interface{}) error {
	if value == nil {
		ns.ImagePurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImagePurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImagePurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImagePurpose), nil
}

func (e ImagePurpose) Valid() bool {
	switch e {
	case ImagePurposeDetect,
		ImagePurposeEmbed,
		ImagePurposeCritique,
		ImagePurposeSegment:
		return true
	}
	return false
}

func AllImagePurposeValues() []ImagePurpose {
	return []ImagePurpose{
		ImagePurposeDetect,
		ImagePurposeEmbed,
		ImagePurposeCritique,
		ImagePurposeSegment,
	}
}

type ObservedFitSource string

const (
	ObservedFitSourceMirror ObservedFitSource = "mirror"
	ObservedFitSourcePhone  ObservedFitSource = "phone"
)

func (e *ObservedFitSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ObservedFitSource(s)
	case string:
		*e = ObservedFitSource(s)
	default:
		return fmt.Errorf("unsupported scan type for ObservedFitSource: %T", src)
	}
	return nil
}

type NullObservedFitSource struct {
	ObservedFitSource ObservedFitSource
	Valid             bool // Valid is true if ObservedFitSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullObservedFitSource) Scan(value interface{}) error {
	if value == nil {
		ns.ObservedFitSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ObservedFitSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullObservedFitSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ObservedFitSource), nil
}

func (e ObservedFitSource) Valid() bool {
	switch e {
	case ObservedFitSourceMirror,
		ObservedFitSourcePhone:
		return true
	}
	return false
}

func AllObservedFitSourceValues() []ObservedFitSource {
	return []ObservedFitSource{
		ObservedFitSourceMirror,
		ObservedFitSourcePhone,
	}
}

type ObservedFitStatus string

const (
	ObservedFitStatusOpen      ObservedFitStatus = "open"
	ObservedFitStatusConfirmed ObservedFitStatus = "confirmed"
	ObservedFitStatusDiscarded ObservedFitStatus = "discarded"
)

func (e *ObservedFitStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ObservedFitStatus(s)
	case string:
		*e = ObservedFitStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ObservedFitStatus: %T", src)
	}
	return nil
}

type NullObservedFitStatus struct {
	ObservedFitStatus ObservedFitStatus
	Valid             bool // Valid is true if ObservedFitStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullObservedFitStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ObservedFitStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ObservedFitStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullObservedFitStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ObservedFitStatus), nil
}

func (e ObservedFitStatus) Valid() bool {
	switch e {
	case ObservedFitStatusOpen,
		ObservedFitStatusConfirmed,
		ObservedFitStatusDiscarded:
		return true
	}
	return false
}

func AllObservedFitStatusValues() []ObservedFitStatus {
	return []ObservedFitStatus{
		ObservedFitStatusOpen,
		ObservedFitStatusConfirmed,
		ObservedFitStatusDiscarded,
	}
}

type OutfitRole string

const (
	OutfitRoleTop       OutfitRole = "top"
	OutfitRoleBottom    OutfitRole = "bottom"
	OutfitRoleOnePiece  OutfitRole = "one_piece"
	OutfitRoleOuterwear OutfitRole = "outerwear"
	OutfitRoleFootwear  OutfitRole = "footwear"
	OutfitRoleAccessory OutfitRole = "accessory"
)

func (e *OutfitRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutfitRole(s)
	case string:
		*e = OutfitRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OutfitRole: %T", src)
	}
	return nil
}

type NullOutfitRole struct {
	OutfitRole OutfitRole
	Valid      bool // Valid is true if OutfitRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutfitRole) Scan(value interface{}) error {
	if value == nil {
		ns.OutfitRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutfitRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutfitRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutfitRole), nil
}

func (e OutfitRole) Valid() bool {
	switch e {
	case OutfitRoleTop,
		OutfitRoleBottom,
		OutfitRoleOnePiece,
		OutfitRoleOuterwear,
		OutfitRoleFootwear,
		OutfitRoleAccessory:
		return true
	}
	return false
}

func AllOutfitRoleValues() []OutfitRole {
	return []OutfitRole{
		OutfitRoleTop,
		OutfitRoleBottom,
		OutfitRoleOnePiece,
		OutfitRoleOuterwear,
		OutfitRoleFootwear,
		OutfitRoleAccessory,
	}
}

type RecommendationEventType string

const (
	RecommendationEventTypeShown             RecommendationEventType = "shown"
	RecommendationEventTypeAccepted          RecommendationEventType = "accepted"
	RecommendationEventTypeRejected          RecommendationEventType = "rejected"
	RecommendationEventTypeItemSwapped       RecommendationEventType = "item_swapped"
	RecommendationEventTypeLoggedAsIs        RecommendationEventType = "logged_as_is"
	RecommendationEventTypeLoggedWithChanges RecommendationEventType = "logged_with_changes"
	RecommendationEventTypeThumbsDown        RecommendationEventType = "thumbs_down"
)

func (e *RecommendationEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecommendationEventType(s)
	case string:
		*e = RecommendationEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for RecommendationEventType: %T", src)
	}
	return nil
}

type NullRecommendationEventType struct {
	RecommendationEventType RecommendationEventType
	Valid                   bool // Valid is true if RecommendationEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecommendationEventType) Scan(value interface{}) error {
	if value == nil {
		ns.RecommendationEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecommendationEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecommendationEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecommendationEventType), nil
}

func (e RecommendationEventType) Valid() bool {
	switch e {
	case RecommendationEventTypeShown,
		RecommendationEventTypeAccepted,
		RecommendationEventTypeRejected,
		RecommendationEventTypeItemSwapped,
		RecommendationEventTypeLoggedAsIs,
		RecommendationEventTypeLoggedWithChanges,
		RecommendationEventTypeThumbsDown:
		return true
	}
	return false
}

func AllRecommendationEventTypeValues() []RecommendationEventType {
	return []RecommendationEventType{
		RecommendationEventTypeShown,
		RecommendationEventTypeAccepted,
		RecommendationEventTypeRejected,
		RecommendationEventTypeItemSwapped,
		RecommendationEventTypeLoggedAsIs,
		RecommendationEventTypeLoggedWithChanges,
		RecommendationEventTypeThumbsDown,
	}
}

type Season string

const (
	SeasonSpring Season = "spring"
	SeasonSummer Season = "summer"
	SeasonFall   Season = "fall"
	SeasonWinter Season = "winter"
)

func (e *Season) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Season(s)
	case string:
		*e = Season(s)
	default:
		return fmt.Errorf("unsupported scan type for Season: %T", src)
	}
	return nil
}

type NullSeason struct {
	Season Season
	Valid  bool // Valid is true if Season is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeason) Scan(value interface{}) error {
	if value == nil {
		ns.Season, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Season.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Season), nil
}

func (e Season) Valid() bool {
	switch e {
	case SeasonSpring,
		SeasonSummer,
		SeasonFall,
		SeasonWinter:
		return true
	}
	return false
}

func AllSeasonValues() []Season {
	return []Season{
		SeasonSpring,
		SeasonSummer,
		SeasonFall,
		SeasonWinter,
	}
}

type AnalysisAsset struct {
	ID            uuid.UUID
	ObservedFitID uuid.UUID
	Kind          AnalysisAssetKind
	ObjectKey     string
	CreatedAt     time.Time
}

type Correction struct {
	ID              uuid.UUID
	CandidateID     uuid.UUID
	PriorResolution CandidateResolution
	FromGarmentID   *uuid.UUID
	ToGarmentID     *uuid.UUID
	CreatedAt       time.Time
}

type Device struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PublicKey []byte
	Name      string
	PairedAt  time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type EmbeddingModel struct {
	Name      string
	Dims      int32
	CreatedAt time.Time
}

type ExemplarEmbedding struct {
	ExemplarID uuid.UUID
	Model      string
	Embedding  pgvector.Vector
	CreatedAt  time.Time
}

type Garment struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Category       GarmentCategory
	Role           OutfitRole
	Name           string
	Brand          *string
	Color          *string
	ColorFamily    ColorFamily
	Pattern        *GarmentPattern
	Material       *GarmentMaterial
	Fit            *GarmentFit
	SeasonTags     []Season
	Warmth         *int16
	WashAfterWears *int16
	PriceMinor     *int64
	Currency       *string
	CreatedFrom    CaptureSource
	ArchivedAt     *time.Time
	DeletedAt      *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GarmentExemplar struct {
	ID             uuid.UUID
	GarmentID      uuid.UUID
	ImageKey       string
	CaptureSource  CaptureSource
	CreationReason ExemplarCreationReason
	Quality        *float64
	CandidateID    *uuid.UUID
	CreatedAt      time.Time
}

type ImageAuditLog struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ObservedFitID *uuid.UUID
	GarmentID     *uuid.UUID
	DeviceID      *uuid.UUID
	ImageKind     ImageKind
	Purpose       ImagePurpose
	Provider      string
	CreatedAt     time.Time
}

type ObservedFit struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DeviceID  *uuid.UUID
	SessionID string
	Source    ObservedFitSource
	Status    ObservedFitStatus
	ExpiresAt time.Time
	ClosedAt  *time.Time
	CreatedAt time.Time
}

type Outfit struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	FromObservedFitID     *uuid.UUID
	FromSuggestedOutfitID *uuid.UUID
	IdempotencyKey        string
	HistoryPhotoKey       *string
	WornAt                time.Time
	LoggedAt              time.Time
	Timezone              string
	LoggedOn              pgtype.Date
	CreatedAt             time.Time
}

type OutfitItem struct {
	OutfitID      uuid.UUID
	GarmentID     uuid.UUID
	Role          *OutfitRole
	LayerPosition *int16
	CreatedAt     time.Time
}

type RecognitionAlternative struct {
	CandidateID uuid.UUID
	GarmentID   uuid.UUID
	Rank        int16
	Similarity  float64
	CreatedAt   time.Time
}

type RecognitionCandidate struct {
	ID                 uuid.UUID
	ObservedFitID      uuid.UUID
	AnalysisAssetID    *uuid.UUID
	DetectedCategory   *GarmentCategory
	BestMatchGarmentID *uuid.UUID
	Score              float64
	ScoreInputs        json.RawMessage
	RecognizerVersion  string
	Resolution         CandidateResolution
	ResolvedGarmentID  *uuid.UUID
	ResolvedAt         *time.Time
	TraceID            *string
	CreatedAt          time.Time
}

type RecommendationEvent struct {
	ID                uuid.UUID
	SuggestedOutfitID uuid.UUID
	Type              RecommendationEventType
	Role              *OutfitRole
	FromGarmentID     *uuid.UUID
	ToGarmentID       *uuid.UUID
	Detail            json.RawMessage
	CreatedAt         time.Time
}

type StyleProfile struct {
	UserID                uuid.UUID
	ExcludedCategories    []GarmentCategory
	ExcludedColorFamilies []ColorFamily
	Notes                 []string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type StyleProfileExcludedGarment struct {
	UserID    uuid.UUID
	GarmentID uuid.UUID
	CreatedAt time.Time
}

type SuggestedOutfit struct {
	ID           uuid.UUID
	SuggestionID uuid.UUID
	Rank         int16
	Score        float64
	Explanation  string
	CreatedAt    time.Time
}

type SuggestedOutfitItem struct {
	SuggestedOutfitID uuid.UUID
	GarmentID         uuid.UUID
	Role              OutfitRole
	Position          int16
	CreatedAt         time.Time
}

type Suggestion struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	RequestText     *string
	WeatherSnapshot json.RawMessage
	Model           string
	PromptVersion   string
	SuggestVersion  string
	TraceID         *string
	CreatedAt       time.Time
}

type User struct {
	ID              uuid.UUID
	AppleSub        *string
	Timezone        string
	WeatherLocation *string
	WeatherLat      *float64
	WeatherLon      *float64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type WashEvent struct {
	ID        uuid.UUID
	GarmentID uuid.UUID
	WashedAt  time.Time
	CreatedAt time.Time
}
