// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const bindUser = `-- name: BindUser :exec
SELECT set_config('vird.user_id', ($1::uuid)::text, true)
`

// BindUser names the user the current transaction acts for. Row-level
// security on every table reads this setting and fails closed, so it must be
// the first statement of every user-facing transaction. The setting is
// transaction-local (is_local = true): it ends with the transaction and never
// leaks to the next request on the same pooled connection.
func (q *Queries) BindUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, bindUser, userID)
	return err
}
